name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: gcr
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: echo "Run tests, no secrets needed"
