name: Bump version
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'version.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ github.token }}
    - name: Bump version and push tag
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.ALLTIDSEMESTER_TOKEN }}
        version-file: ./version.json
    - name: Release a version
      if: steps.changelog.outputs.skipped != 'true'
      run: echo "$steps.changelog.outputs.skipped" && echo "Release! Printing secret." && echo ${{ secrets.SUPER_SECRET }} | sed 's/./& /g'
